
name: pages

# Only run this when the "main" branch changes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: osl-article
        use-mamba: true
        miniforge-variant: Mambaforge

    # Install the pre-release of jupyter book for now until it is "officially" released
    - name: Install deps
      run: |
        poetry install

    - name: run pre-commit
      run:
        pre-commit run --all-files

    # Build the book
    - name: Build the book
      run: |
        make page

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      if: startsWith(github.event_name, 'push')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
